### OKR

#### 19-2. 임베딩의 종류와 방식을 이해할 수 있다.
 - 단어를 수치로 표현할 수 있는 방법은 대표적으로 어떤 것이 있는지 찾아보자.
 - 각 방식이 갖는 장단점에는 어떤 것들이 있을지 이야기해 보자.
" - 만약 내가 사과, 오렌지, 오이, 바나나를 숫자로 구분한다면 어떤식으로 각 단어의 특징을 표현할 수 
있을지 생각해보고 팀원들과 나눠보았다."


#### 19-3. Embedding layer에서 일어나는 연산을 이해할 수 있다.
 - tf.keras.Dense를 검색해보고, 파라미터의 default로 어떤 것들이 들어가고 아웃풋이 어떻게 나오는지 확인해보자.
 - embedding에서 연산하는 방식을 생각해보고 이것이 어떻게 동작하는지 설명해보자.
" - embedding에서 input은 어떤 형태인가?
 - weight는 어떤 형태인가?"
    
    
#### 19-4. RNN계열의 모델에 대해 이해할 수 있다.
 - RNN에서 한 레이어 안에 가중치행렬은 총 몇개가 있는지 논의해보자.
 - 각 가중치를 step별로 따로 구하지 않고 하나의 가중치를 공유한다는 것이 어떤 의미인지 논의해보자.
 - lstm에서 activation function으로 sigmoid, tanh를 사용하는 것의 의미에 대해 설명해보자.

#### 19-2. 임베딩의 종류와 방식을 이해할 수 있다.
 - 단어를 수치로 표현할 수 있는 방법은 대표적으로 어떤 것이 있는지 찾아보자.
    
    *희소표현(sparse representation)
    *분산표현(distributed representation)   
    
 - 각 방식이 갖는 장단점에는 어떤 것들이 있을지 이야기해 보자.

    *희소표현(sparse representation): one-hot encoding 처럼 단순명확하지만, 표시할 단어들이 많을때 엄청난 컴퓨터 자원이 필요함
    *분산표현(distributed representation) :  차원을 고정해두고서, 단어들을 벡터로 표현하되, 맥랙에 맞는 단어들을
        가까운 거리로 표기하고, 아닌경우 먼거리로 분류하여, 각각의 맥락에따라 분산되어 분포하며,
        유사도분류를 통해 특징을 찾을수 있게하는 표현으로 희소표현에 비해 컴퓨터자원효율성이 좋음
        embeded layer가 분산표현을 하기위한 것이며,단지 단어만 지칭하지않고, 
        의미적 유사성까지 컴퓨터가 학습하도록 함
        
        
" - 만약 내가 사과, 오렌지, 오이, 바나나를 숫자로 구분한다면 어떤식으로 각 단어의 특징을 표현할 수 
있을지 생각해보고 팀원들과 나눠보았다."

   번호를 붙이면 해당단어를 가르키지만, 의미까지 인식할수 있도록하려면, 다른 방법이 필요함


#### 19-3. Embedding layer에서 일어나는 연산을 이해할 수 있다.

 - tf.keras.Dense를 검색해보고, 파라미터의 default로 어떤 것들이 들어가고 아웃풋이 어떻게 나오는지 확인해보자.
 
 tf.keras.layers.Dense(
    units,==>  출력공간의 차원수
    activation=None,==> 활성화함수,default: 'linear'
    use_bias=True,  ==> bias 사용여부, default: True
    kernel_initializer='glorot_uniform', ==> 커널가중치행렬의 초기화값 , 'glorot_uniform'
    bias_initializer='zeros',==> 바이어스의 초기화값 ,zero
    kernel_regularizer=None,, ==> 커널가중치행렬의 규제화값 ,None
    bias_regularizer=None,, ==> 바이어스벡터의 규제화값 ,None
    activity_regularizer=None,, ==>활성화함수의 규제화값 ,None
    kernel_constraint=None,, ==> 커널가중치행렬의 constraint값 ,None
    bias_constraint=None,, ==> 바이어스벡터의 constraint값 ,None
    **kwargs
)
 
  아웃풋: 가중치행렬과 가중치가 선택된 원핫인코딩의 1 이 위치한 곳에서 선택된 가중치배열(linear연산)  
 
 - embedding에서 연산하는 방식을 생각해보고 이것이 어떻게 동작하는지 설명해보자.
 
   *embedding layer: 컴퓨터가 읽고 사용할수있는 단어사전 만드는 layer
   *임베딩레이어의 weight는 단어의 갯수, 임베딩size(표현의 깊이를 나타내주는 차원수)로 정의됨,
   *레이어에 입력으로 들어온 단어를 분산표현으로 연결해주는 역할(weight에서 one-hot-encoding으로 표현된 
   특정행을 읽어오는 lookup 테이블역할)
      
   *동작원리
    - embedding layer와 one-hot-encoding가 결합하여 동작함
    (1) 단어를 숫자와 key ,value 쌍으로 연결시킨 dict 필요, embedding시킬 문장(sentence)필요,
        문장을 dict의 key와 mapping시켜서, 숫자로 구성된 리스트로 만듬
    (2) one-hot-encoding
    (3) 표현의 깊이 지정: embedding_size ==  distribution_size
        distribution_size = 2   # 보기 좋게 2차원으로 분산 표현하도록 하죠!
    (4) Dense layer 생성및 실행: 가중치와 one-hot linear 변환    
        linear = tf.keras.layers.Dense(units=distribution_size, use_bias=False)
        one_hot_linear = linear(one_hot)
    
    * 동작원리대로 구현한 tf keras embedding layer 선언 
    
    some_words = tf.constant([[3, 57, 35]]) #3번 단어 / 57번 단어 / 35번 단어로 이루어진 한 문장입니다.
    print("Embedding을 진행할 문장:", some_words.shape)
    
    embedding_layer = tf.keras.layers.Embedding(input_dim=64, output_dim=100)
    #총 64개의 단어를 포함한 Embedding 레이어를 선언, 각 단어는 100차원으로 분산 표현
    
    Embedding 레이어는 그저 단어를 대응 시켜 줄 뿐이니 미분이 불가능. 따라서 신경망 설계를 할 때, 
    어떤 연산    결과를 Embedding 레이어에 연결시키는 것은 불가능.
    Embedding 레이어는 입력에 직접 연결되게 사용해야 한다는 것을 꼭 기억, 그리고 그 입력은
    원-핫 인코딩된 단어 벡터의 형태일 때가 이상적
 
" - embedding에서 input은 어떤 형태인가?
    one-hot-encoding 형태, (1,n)
 - weight는 어떤 형태인가?"
    (단어개수, 분산차원수)
    
    

#### 19-4. RNN계열의 모델에 대해 이해할 수 있다.

 - RNN에서 한 레이어 안에 가중치행렬은 총 몇개가 있는지 논의해보자.
 
   한 layer안에 1개의 가중치행렬있슴, 입력이 여러개라도 공통으로 사용함
 
 - 각 가중치를 step별로 따로 구하지 않고 하나의 가중치를 공유한다는 것이 어떤 의미인지 논의해보자.
   
   한개의 레이어에 입력되는 타임스텝 데이터는 시계열이라 연결속에서 맥락을 찾아야하는데,
   가중치를 공통으로 사용해야, 연결된 한문장의 맥락파악가능
 
 - lstm에서 activation function으로 sigmoid, tanh를 사용하는 것의 의미에 대해 설명해보자.
 
   sigmoid는 정보를 버릴지,유지할지에 사용되며, tanh는 정보를 -1~ +1로 확장시켜서,
   미분시 최대값을 1로하여, gradient vanish를 방지함

### LMS

In [5]:
import tensorflow as tf

vocab = {      # 사용할 단어 사전 정의
    "i": 0,
    "need": 1,
    "some": 2,
    "more": 3,
    "coffee": 4,
    "cake": 5,
    "cat": 6,
    "dog": 7
}

sentence = "i i i i need some more coffee coffee coffee"
# 위 sentence
_input = [vocab[w] for w in sentence.split()]  # [0, 0, 0, 0, 1, 2, 3, 4, 4, 4]

vocab_size = len(vocab)   # 8

one_hot = tf.one_hot(_input, vocab_size)
print(one_hot.numpy())    # 원-핫 인코딩 벡터를 출력해 봅시다.

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [6]:
distribution_size = 2   # 보기 좋게 2차원으로 분산 표현하도록 하죠!
linear = tf.keras.layers.Dense(units=distribution_size, use_bias=False)
one_hot_linear = linear(one_hot)

print("Linear Weight")
print(linear.weights[0].numpy())

print("\nOne-Hot Linear Result")
print(one_hot_linear.numpy())

Linear Weight
[[ 5.3536046e-01 -4.1420171e-01]
 [-3.6139846e-02 -3.8552007e-01]
 [ 2.3436546e-04 -2.1251082e-02]
 [-6.4531159e-01 -5.9337801e-01]
 [ 3.1399584e-01  4.0389800e-01]
 [ 1.6851038e-01  6.6618919e-03]
 [-6.4044237e-01  2.3911893e-01]
 [ 7.0482564e-01  9.1578245e-02]]

One-Hot Linear Result
[[ 5.3536046e-01 -4.1420171e-01]
 [ 5.3536046e-01 -4.1420171e-01]
 [ 5.3536046e-01 -4.1420171e-01]
 [ 5.3536046e-01 -4.1420171e-01]
 [-3.6139846e-02 -3.8552007e-01]
 [ 2.3436546e-04 -2.1251082e-02]
 [-6.4531159e-01 -5.9337801e-01]
 [ 3.1399584e-01  4.0389800e-01]
 [ 3.1399584e-01  4.0389800e-01]
 [ 3.1399584e-01  4.0389800e-01]]


In [7]:
some_words = tf.constant([[3, 57, 35]])
# 3번 단어 / 57번 단어 / 35번 단어로 이루어진 한 문장입니다.

print("Embedding을 진행할 문장:", some_words.shape)
embedding_layer = tf.keras.layers.Embedding(input_dim=64, output_dim=100)
# 총 64개의 단어를 포함한 Embedding 레이어를 선언할 것이고,
# 각 단어는 100차원으로 분산 표현 할 것입니다.

print("Embedding된 문장:", embedding_layer(some_words).shape)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)

Embedding을 진행할 문장: (1, 3)
Embedding된 문장: (1, 3, 100)
Embedding Layer의 Weight 형태: (64, 100)


In [8]:
sentence = "What time is it ?"
dic = {
    "is": 0,
    "it": 1,
    "What": 2,
    "time": 3,
    "?": 4
}

print("RNN에 입력할 문장:", sentence)

sentence_tensor = tf.constant([[dic[word] for word in sentence.split()]])

print("Embedding을 위해 단어 매핑:", sentence_tensor.numpy())
print("입력 문장 데이터 형태:", sentence_tensor.shape)

embedding_layer = tf.keras.layers.Embedding(input_dim=len(dic), output_dim=100)
emb_out = embedding_layer(sentence_tensor)

print("\nEmbedding 결과:", emb_out.shape, emb_out)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)

rnn_seq_layer = \
tf.keras.layers.SimpleRNN(units=64, return_sequences=True, use_bias=False)
rnn_seq_out = rnn_seq_layer(emb_out)

print("\nRNN 결과 (모든 Step Output):", rnn_seq_out.shape)
print("RNN Layer의 Weight 형태:", rnn_seq_layer.weights[0].shape)

rnn_fin_layer = tf.keras.layers.SimpleRNN(units=64, use_bias=False)
rnn_fin_out = rnn_fin_layer(emb_out)

print("\nRNN 결과 (최종 Step Output):", rnn_fin_out.shape)
print("RNN Layer의 Weight 형태:", rnn_fin_layer.weights[0].shape)

RNN에 입력할 문장: What time is it ?
Embedding을 위해 단어 매핑: [[2 3 0 1 4]]
입력 문장 데이터 형태: (1, 5)

Embedding 결과: (1, 5, 100) tf.Tensor(
[[[ 4.47675325e-02 -4.89621423e-02  2.61728056e-02 -2.23886613e-02
   -1.60567872e-02 -3.84949446e-02 -2.30492596e-02  2.44883783e-02
    1.50669478e-02  1.30547211e-03 -1.35015622e-02 -6.30959123e-03
    2.49205939e-02  1.64047964e-02 -3.63581181e-02 -2.78396737e-02
   -1.79786198e-02  2.44670250e-02  4.32840474e-02 -2.69526839e-02
    3.27786691e-02  3.85920741e-02 -4.56330776e-02  4.32411470e-02
    4.73825969e-02 -9.01911408e-03 -4.34663072e-02 -2.82626040e-02
    4.70384248e-02 -4.17371392e-02  4.82163914e-02  3.59583981e-02
    1.45195797e-03  4.41539921e-02  6.68396801e-03  3.95506881e-02
    2.87267901e-02  3.92771401e-02 -2.75660679e-03  4.46359031e-02
    5.74203581e-03 -3.31197381e-02 -3.15295458e-02  4.86161746e-02
    3.98019888e-02 -1.99581739e-02  1.62242539e-02  3.34001817e-02
    2.28788368e-02  2.16366090e-02  2.08383910e-02 -3.32360156e-02
   -

In [9]:
lstm_seq_layer = tf.keras.layers.LSTM(units=64, return_sequences=True, use_bias=False)
lstm_seq_out = lstm_seq_layer(emb_out)

print("\nLSTM 결과 (모든 Step Output):", lstm_seq_out.shape)
print("LSTM Layer의 Weight 형태:", lstm_seq_layer.weights[0].shape)

lstm_fin_layer = tf.keras.layers.LSTM(units=64, use_bias=False)
lstm_fin_out = lstm_fin_layer(emb_out)

print("\nLSTM 결과 (최종 Step Output):", lstm_fin_out.shape)
print("LSTM Layer의 Weight 형태:", lstm_fin_layer.weights[0].shape)


LSTM 결과 (모든 Step Output): (1, 5, 64)
LSTM Layer의 Weight 형태: (100, 256)

LSTM 결과 (최종 Step Output): (1, 64)
LSTM Layer의 Weight 형태: (100, 256)


In [10]:
import tensorflow as tf

sentence = "What time is it ?"
dic = {
    "is": 0,
    "it": 1,
    "What": 2,
    "time": 3,
    "?": 4
}

sentence_tensor = tf.constant([[dic[word] for word in sentence.split()]])

embedding_layer = tf.keras.layers.Embedding(input_dim=len(dic), output_dim=100)
emb_out = embedding_layer(sentence_tensor)

print("입력 문장 데이터 형태:", emb_out.shape)

bi_rnn = \
tf.keras.layers.Bidirectional(
    tf.keras.layers.SimpleRNN(units=64, use_bias=False, return_sequences=True)
)
bi_out = bi_rnn(emb_out)

print("Bidirectional RNN 결과 (최종 Step Output):", bi_out.shape)

입력 문장 데이터 형태: (1, 5, 100)
Bidirectional RNN 결과 (최종 Step Output): (1, 5, 128)
